# Generated by Django 3.2.16 on 2023-01-28 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='images',
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('phone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.phone')),
            ],
        ),
    ]
