# Generated by Django 3.2.16 on 2023-01-30 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20230128_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneimage',
            name='phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.phone'),
        ),
    ]
